### PR TITLE
Add `--ignore-overloaded-functions` flag to ignore overload decorators

### LINKED ISSUE #97: Option to ignore overloaded functions
### Describe the feature you'd like
When decorating functions with `@typing.overload`, the stubs are marked as not covered when they don't have their own docstring. My suggestion is to add an option to ignore those stubs.

### Is your feature request related to a problem?
We have overloaded functions in our codebase that we want to start using this package in and we only document the actual implementation and not the stubs.

### Your Environment
- `interrogate` version(s) (`interrogate --version`: 1.5.0
- Operating System(s): linux
- Python version(s): 3.6-3.10

### Additional context
PR incoming.

### PR DESCRIPTION
**Pull request by ErwinJunge**
# Hey, I just made a Pull Request!

## Description
Add `--ignore-overloaded-functions` flag to ignore overload decorators

## Motivation and Context
Fixes #97

## Have you tested this? If so, how?
I have included unittests and ran `interrogate` against a codebase with overloads.

## Checklist for PR author(s)

- [x] Changes are covered by unit tests (no major decrease in code coverage %).
- [x] All tests pass.
- [x] Docstring coverage is **100%** via `tox -e docs` or `interrogate -c pyproject.toml` (I mean, we _should_ set a good example :smile:).
- [x] Updates to documentation:
    - [x] Document any relevant additions/changes in `README.rst`.
    - [x] Manually update **both** the `README.rst` _and_ `docs/index.rst` for any new/changed CLI flags.
    - [x] Any changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` [directives](http://www.sphinx-doc.org/en/stable/markup/para.html#directive-versionadded).  Find the appropriate next version in the project's [``__init__.py``](https://github.com/econchick/interrogate/blob/master/src/interrogate/__init__.py) file.

## Release note

```release-note
Add ``--ignore-overloaded-functions`` flag to ignore overload decorators (`#97 <https://github.com/econchick/interrogate/issues/97>`_).
```

### CODE REVIEW

**Comment by econchick** [comment]
dang! thanks for the contribution @ErwinJunge ! I'm wrapping up a bunch of work stuff, but I'll review this over the next few days. Thanks!

**Comment by ErwinJunge** [comment]
Apparently I failed at running black :facepalm: 

I've fixed the codestyle and forcepushed a new commit.

**Comment by ErwinJunge** [comment]
> dang! thanks for the contribution @ErwinJunge ! I'm wrapping up a bunch of work stuff, but I'll review this over the next few days. Thanks!

For me this is work stuff :) I'm finishing up my week now and will pick this back up monday if there's any feedback.

**Comment by ErwinJunge** [comment]
@econchick friendly ping on the review :)

**Review by econchick — CHANGES_REQUESTED** [review]
Hey @ErwinJunge ! So sorry for the delay - I actually caught covid last week 🤦🏻‍♀️ 

This looks great to me! I appreciate the thoroughness of this PR too - I'm sure you're annoyed at my testing suite 😅 

I just have one request: Would you mind being more descriptive with the user-facing help text for the option? As in, something more specific like "Ignore `@typing.overload`-decorated functions." (in `cli.py`, `README.rst`, `docs/index.rst`, and the docstring in `config.py`). I'm sure someone who's familiar with `typing` understands what overloaded functions means, but for those that are not (yet) familiar, it may seem confusing that Python supports overloaded functions.

**Comment by ErwinJunge** [comment]
Hi @econchick , I'm sorry to hear about the covid and I hope you had a full recovery!

You're welcome for the PR. The test suite could indeed use some work, there were a lot of unrelated testing changes required to add my new thing. However, on the whole I'm mostly just happy there *is* a test suite! :smile: 

Thank you for the review and the improvement suggestion. I've implemented it in the update I've just pushed.

**Review by econchick — APPROVED** [review]
Thanks again @ErwinJunge ! I'm not sure when 1.6.0 will be released (but not longer than a week or two - want to see if I can get in another feature). But I'll ping this thread when I have.

If you happen to be at PyCon US in 2022, find me - I'll have stickers!

**Comment by econchick** [comment]
uff - @ErwinJunge , looks like that small change broke some tests 😬 If you don't have time to fix them in the next couple of days, I can try to dig in. (This indeed makes me want to rewrite the test suite 🤦🏻)

**Comment by ErwinJunge** [comment]
Tests updated in latest push.

Re: pycon US, thanks for the offer but I don't think that'll be likely :) I live in the Netherlands, and it's currently a bit hard to travel out of Europe :sweat_smile:

**Comment by ErwinJunge** [comment]
@econchick those test failures look like the docstring coverage results are different on windows than they are on linux :confused: I don't have a windows box available to run those tests locally and can't imagine what would make the results different on windows so I don't think I'll be able to fix these.

**Comment by ErwinJunge** [comment]
@econchick do you have some input on the windows tests? Is there perhaps something I can do without having access to a windows box?

**Comment by ErwinJunge** [comment]
@econchick I took a closer look today and what's failing are the test expectation files in `tests/functional/fixtures/windows/` I didn't update those (because I got all green on my machine :sweat_smile: ). However, I don't think I can update these, since I don't have access to a windows box to recreate them on. I tried copy-pasting the non-windows files and checking what changed using git diff, but that indicates the entire file is different (including stuff like the first line that definitely didn't change). There's some windows-specific magic going on that I can't replicate without access to a windows box. Can you regenerate those files and update the PR for me? 

What I did for the linux files is this:

1. Add the below into a relevant test
```
    with open(expected_fixture, "w") as f:
        f.write(expected_out)
```
2. Sanity check the git diff. There might be added lines that shouldn't be there, remove those. Make sure there are only changed lines that make sense according to the python changes in the PR.
3. Once the diff is clean: commit :)

**Comment by ErwinJunge** [comment]
@econchick friendly ping on the above :) Please let me know if there's anything I can do to move this along.

**Comment by erwin-eiq** [comment]
:wave: @econchick please don't forget about this one :pleading_face:

**Comment by ErwinJunge** [comment]
:wave: @econchick please don't forget about this one :pleading_face:

**Comment by conrad-stork** [comment]
Hi All,

I found this pull request as I the same problem with interrogate. My question would be if there is any chance that this pull request is merged at some point? I think this could be very useful feature.

Thanks and Best

**Pull request merged**
