### PR TITLE
Fix windows tests for #98: ignoring @overload decorated functions

### LINKED ISSUE #97: Option to ignore overloaded functions
### Describe the feature you'd like
When decorating functions with `@typing.overload`, the stubs are marked as not covered when they don't have their own docstring. My suggestion is to add an option to ignore those stubs.

### Is your feature request related to a problem?
We have overloaded functions in our codebase that we want to start using this package in and we only document the actual implementation and not the stubs.

### Your Environment
- `interrogate` version(s) (`interrogate --version`: 1.5.0
- Operating System(s): linux
- Python version(s): 3.6-3.10

### Additional context
PR incoming.

### PR DESCRIPTION
**Pull request by zackyancey**
## Description
This is just the changes by @ErwinJunge in #98, with the expected results for the windows tests updated.

(let me know if I should be somehow adding this to #98 instead, I'm not sure how I'd do that. Or @ErwinJunge if you just want to add these to your branch that would work too).

## Motivation and Context
Allows #98 to be merged, which fixes #97

## Have you tested this? If so, how?
I've run the tests put in by @ErwinJunge on linux and windows, and run the changes against my own code.

## Checklist for PR author(s)

- [X] Changes are covered by unit tests (no major decrease in code coverage %).
- [X] All tests pass.
- [X] Docstring coverage is **100%** via `tox -e docs` or `interrogate -c pyproject.toml` (I mean, we _should_ set a good example :smile:).
- [X] Updates to documentation:
    - [X] Document any relevant additions/changes in `README.rst`.
    - [X] Manually update **both** the `README.rst` _and_ `docs/index.rst` for any new/changed CLI flags.
    - [X] Any changed/added classes/methods/functions have appropriate `versionadded`, `versionchanged`, or `deprecated` [directives](http://www.sphinx-doc.org/en/stable/markup/para.html#directive-versionadded).  Find the appropriate next version in the project's [``__init__.py``](https://github.com/econchick/interrogate/blob/master/src/interrogate/__init__.py) file.

## Release note

```release-note
Add ``--ignore-overloaded-functions`` flag to ignore overload decorators (`#97 <https://github.com/econchick/interrogate/issues/97>`_).
```

### CODE REVIEW

**Comment by ErwinJunge** [comment]
@zackyancey thanks so much for taking the time to fix the windows part of the tests :bow: 

I'm fine with merging this instead of #98, since it contains my singular commit from #98 anyways :) 

However, now the pre-commit has started failing on missing interrogate for some reason? :thinking: 

Anyways, you have my full support, let's get this merged!

**Comment by zackyancey** [comment]
Hm, it looks like the same thing is happening on master and on other PRs newer than a couple weeks old. It seems like it might be related to the recent move to pre-commit.ci -- @hynek @econchick any idea what could be causing the precommit to not find interrogate?

**Comment by hynek** [comment]
Yes it's because the local install step doesn't work there. It should be replaced by a normal pre-commit installation and add dog-fooding to Tox.

**Comment by zackyancey** [comment]
That did it, thanks!

**Comment by vpoulailleau** [comment]
Any news on this? (The merge would be perfect for me :wink:)

**Comment by zackyancey** [comment]
As far as I can tell the tests should be passing now -- I think all that's needed to get it merged is review/approval. @econchick am I missing anything here?

**Comment by econchick** [comment]
Thanks for your help! I cherry picked your commits and included them in #167 ❤️

**Pull request closed without merging**
